[package]
name = "leafmark-native"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
dioxus.workspace = true
leafmark-core = { path = "../../crates/leafmark-core" }
leafmark-domain = { path = "../../crates/leafmark-domain" }
leafmark-editor = { path = "../../crates/leafmark-editor" }
leafmark-markdown = { path = "../../crates/leafmark-markdown" }
leafmark-scene = { path = "../../crates/leafmark-scene" }
